---
- name: Standard Infrastructure Maintenance
  hosts: all
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive
    UCF_FORCE_CONFOLD: "true"

  tasks:
    - name: Run apt update and upgrade
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
        dpkg_options: 'force-confold,force-confdef'
      register: apt_output  # This captures the result

    - name: Show the upgraded packages
      ansible.builtin.debug:
        msg: "{{ apt_output.stdout_lines }}"
      when: apt_output.changed  # Only show if something actually happened

    - name: Remove redundant packages
      ansible.builtin.apt:
        autoremove: yes
        purge: yes
      register: autoremove_output

    - name: Show cleanup details
      ansible.builtin.debug:
        msg: "{{ autoremove_output.stdout_lines }}"
      when: autoremove_output.changed
